global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'primary-server'
    static_configs:
      - targets: ['primary-server:5000']
    metrics_path: '/metrics'

  - job_name: 'backup-server'
    static_configs:
      - targets: ['backup-server:5000']
    metrics_path: '/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    